---
name: pre-commit-check
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install prerequisites
        run: |
          brew tap liamg/tfsec
          brew install tfenv tflint terraform-docs pre-commit liamg/tfsec/tfsec
          pre-commit install
          tfenv install min-required
          tfenv use min-required
      - name: initiallize Terraform
        run: terraform init
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys:
            - pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
            - pre-commit
      - name: pre-commit run all
        run: |
          pre-commit run -a
        env:
          AWS_DEFAULT_REGION: us-east-1
          SKIP: terraform_tflint_deep
