---
name: pre-commit-check
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install prerequisites
        run: ./bin/install-macos.sh
      - name: initialize Terraform
        run: terraform init --backend=false
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit
      - name: pre-commit run all
        run: |
          pre-commit run -a
        env:
          AWS_DEFAULT_REGION: us-east-1
          SKIP: terraform_tflint_deep
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ failure() }}
        with:
          commit_message: Apply automatic changes
          commit_options: "--no-verify"
          # Optional commit user and author settings
          commit_user_name: Linter Bot
          commit_user_email: noreply@rhythmictech.com
          commit_author: Linter Bot <actions@github.com>
